# Generated by Django 5.1 on 2024-10-29 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinfo',
            name='keyword',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='generalinfo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
